# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d1fa9cbc5b47b07a856cc181e7a26a358b411b84a99be39b186055dc48bed78b7d3b33b80f8bef25c428aa1d909abf92027e14f65a72677f93c45532ef4579b

test:
  secret_key_base: 4becdcd73770756723599b8975d2993ae39a1309285edb08ba301bd61f61602fd484e9247e1958629056dabe847d8de6fdc7d60d53814b614e0dc41b46724a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
