# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6cd2ad4c710f5d9ac1820b24aa99aeca18c64c7dff2435f55b97d504d0aa2d2cab9ba8ff906ab91cfef7da6329b8b583cdd213cf22fdb582bbed5a8ec33389

test:
  secret_key_base: 3b5f1e4f496ba16bf5abdd87215fed78a90c464af1bacfabeecb5cceb6366e67404a7f560443b182a6c2bd7c4691ad35dfbe2cfed64fbdc92cbc7c1bb5f23097

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
